version: '3.8'
networks:
  private-net:
    driver: bridge
services:
    mongo:
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
      ports:
        - "27017:27017"
      volumes:
        - /.data:/data/db
    sqlserver:
      environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=yourStrong(!)Password
      networks:
        - private-net     
      ports:
          - '1433:1433'
      image: mcr.microsoft.com/mssql/server:2019-latest
    redis:
        image: redis
        command: redis-server --requirepass Redis2019!
        networks:
          - private-net   
        ports:
          - "6379:6379"
volumes:
  PATH:
    driver: local      